// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/tvshow/tvshow_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/Tvshow.dart' as _i10;
import 'package:ditonton/domain/entities/tvshow_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_watchlist_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tvshow/remove_tvshow_watchlist.dart'
    as _i6;
import 'package:ditonton/domain/usecases/tvshow/save_tvshow_watchlist.dart'
    as _i5;
import 'package:ditonton/presentation/provider/tvshow/tvshow_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvshowDetail_0 extends _i1.SmartFake
    implements _i2.GetTvshowDetail {
  _FakeGetTvshowDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvshowRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTvshowRecommendations {
  _FakeGetTvshowRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvshowWatchListStatus_2 extends _i1.SmartFake
    implements _i4.GetTvshowWatchListStatus {
  _FakeGetTvshowWatchListStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveTvshowWatchlist_3 extends _i1.SmartFake
    implements _i5.SaveTvshowWatchlist {
  _FakeSaveTvshowWatchlist_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveTvshowWatchlist_4 extends _i1.SmartFake
    implements _i6.RemoveTvshowWatchlist {
  _FakeRemoveTvshowWatchlist_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvshowDetail_5 extends _i1.SmartFake implements _i7.TvshowDetail {
  _FakeTvshowDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvshowDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowDetailNotifier extends _i1.Mock
    implements _i8.TvshowDetailNotifier {
  MockTvshowDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvshowDetail get getTvshowDetail => (super.noSuchMethod(
        Invocation.getter(#getTvshowDetail),
        returnValue: _FakeGetTvshowDetail_0(
          this,
          Invocation.getter(#getTvshowDetail),
        ),
      ) as _i2.GetTvshowDetail);

  @override
  _i3.GetTvshowRecommendations get getTvshowRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvshowRecommendations),
        returnValue: _FakeGetTvshowRecommendations_1(
          this,
          Invocation.getter(#getTvshowRecommendations),
        ),
      ) as _i3.GetTvshowRecommendations);

  @override
  _i4.GetTvshowWatchListStatus get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetTvshowWatchListStatus_2(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i4.GetTvshowWatchListStatus);

  @override
  _i5.SaveTvshowWatchlist get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveTvshowWatchlist_3(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i5.SaveTvshowWatchlist);

  @override
  _i6.RemoveTvshowWatchlist get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveTvshowWatchlist_4(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i6.RemoveTvshowWatchlist);

  @override
  _i7.TvshowDetail get tvshow => (super.noSuchMethod(
        Invocation.getter(#tvshow),
        returnValue: _FakeTvshowDetail_5(
          this,
          Invocation.getter(#tvshow),
        ),
      ) as _i7.TvshowDetail);

  @override
  _i9.RequestState get tvshowState => (super.noSuchMethod(
        Invocation.getter(#tvshowState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  List<_i10.Tvshow> get tvshowRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvshowRecommendations),
        returnValue: <_i10.Tvshow>[],
      ) as List<_i10.Tvshow>);

  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> fetchTvshowDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvshowDetail,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addWatchlist(_i7.TvshowDetail? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvshow],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeFromWatchlist(_i7.TvshowDetail? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvshow],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
