// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/provider/tvshow/tvshow_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/Tvshow.dart' as _i9;
import 'package:ditonton/domain/entities/tvshow_detail.dart' as _i7;
import 'package:ditonton/domain/repositories/tvshow_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_detail.dart' as _i4;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_recommendations.dart'
    as _i8;
import 'package:ditonton/domain/usecases/tvshow/get_tvshow_watchlist_status.dart'
    as _i10;
import 'package:ditonton/domain/usecases/tvshow/remove_tvshow_watchlist.dart'
    as _i12;
import 'package:ditonton/domain/usecases/tvshow/save_tvshow_watchlist.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvshowRepository_0 extends _i1.SmartFake
    implements _i2.TvshowRepository {
  _FakeTvshowRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTvshowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvshowDetail extends _i1.Mock implements _i4.GetTvshowDetail {
  MockGetTvshowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvshowDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.TvshowDetail>>.value(
                _FakeEither_1<_i6.Failure, _i7.TvshowDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.TvshowDetail>>);
}

/// A class which mocks [GetTvshowRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvshowRecommendations extends _i1.Mock
    implements _i8.GetTvshowRecommendations {
  MockGetTvshowRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.Tvshow>>> execute(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i9.Tvshow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i9.Tvshow>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.Tvshow>>>);
}

/// A class which mocks [GetTvshowWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvshowWatchListStatus extends _i1.Mock
    implements _i10.GetTvshowWatchListStatus {
  MockGetTvshowWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);

  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveTvshowWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTvshowWatchlist extends _i1.Mock
    implements _i11.SaveTvshowWatchlist {
  MockSaveTvshowWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvshowDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [movie],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [movie],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveTvshowWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTvshowWatchlist extends _i1.Mock
    implements _i12.RemoveTvshowWatchlist {
  MockRemoveTvshowWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvshowDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [movie],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [movie],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
