// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i26;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i9;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i17;
import 'package:ditonton/data/datasources/local_data_source.dart' as _i14;
import 'package:ditonton/data/datasources/movie/movie_remote_data_source.dart'
    as _i12;
import 'package:ditonton/data/datasources/tvshow/tvshow_remote_data_source.dart'
    as _i19;
import 'package:ditonton/data/models/movie/movie_detail_response.dart' as _i3;
import 'package:ditonton/data/models/movie/movie_model.dart' as _i13;
import 'package:ditonton/data/models/tvshow/season_detail_response.dart' as _i5;
import 'package:ditonton/data/models/tvshow/tvshow_detail_response.dart' as _i4;
import 'package:ditonton/data/models/tvshow/tvshow_model.dart' as _i20;
import 'package:ditonton/data/models/watchlist_table.dart' as _i15;
import 'package:ditonton/domain/entities/movie.dart' as _i10;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i11;
import 'package:ditonton/domain/entities/season_detail.dart' as _i24;
import 'package:ditonton/domain/entities/Tvshow.dart' as _i22;
import 'package:ditonton/domain/entities/tvshow_detail.dart' as _i23;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i7;
import 'package:ditonton/domain/repositories/tvshow_repository.dart' as _i21;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvshowDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvshowDetailResponse {
  _FakeTvshowDetailResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonDetailResponse_3 extends _i1.SmartFake
    implements _i5.SeasonDetailResponse {
  _FakeSeasonDetailResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i7.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #getNowPlayingMovies,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>.value(
                _FakeEither_0<_i9.Failure, _i11.MovieDetail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #getMovieRecommendations,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
          this,
          Invocation.method(
            #getWatchlistMovies,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i12.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i8.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i3.MovieDetailResponse>);

  @override
  _i8.Future<List<_i13.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
      ) as _i8.Future<List<_i13.MovieModel>>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i14.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i15.WatchlistTable? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [data],
        ),
        returnValue: _i8.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [data],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> removeWatchlist(_i15.WatchlistTable? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [data],
        ),
        returnValue: _i8.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [data],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i15.WatchlistTable?> getDataById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getDataById,
          [id],
        ),
        returnValue: _i8.Future<_i15.WatchlistTable?>.value(),
      ) as _i8.Future<_i15.WatchlistTable?>);

  @override
  _i8.Future<List<_i15.WatchlistTable>> getWatchlistData(String? tipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistData,
          [tipe],
        ),
        returnValue: _i8.Future<List<_i15.WatchlistTable>>.value(
            <_i15.WatchlistTable>[]),
      ) as _i8.Future<List<_i15.WatchlistTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i17.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i18.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i8.Future<_i18.Database?>.value(),
      ) as _i8.Future<_i18.Database?>);

  @override
  _i8.Future<int> insertWatchlist(_i15.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> removeWatchlist(_i15.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistMovies(String? tipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [tipe],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvshowRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowRemoteDataSource extends _i1.Mock
    implements _i19.TvshowRemoteDataSource {
  MockTvshowRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i20.TvshowModel>> getNowPlayingTvshow() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTvshow,
          [],
        ),
        returnValue:
            _i8.Future<List<_i20.TvshowModel>>.value(<_i20.TvshowModel>[]),
      ) as _i8.Future<List<_i20.TvshowModel>>);

  @override
  _i8.Future<List<_i20.TvshowModel>> getPopularTvshow() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTvshow,
          [],
        ),
        returnValue:
            _i8.Future<List<_i20.TvshowModel>>.value(<_i20.TvshowModel>[]),
      ) as _i8.Future<List<_i20.TvshowModel>>);

  @override
  _i8.Future<List<_i20.TvshowModel>> getTopRatedTvshow() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvshow,
          [],
        ),
        returnValue:
            _i8.Future<List<_i20.TvshowModel>>.value(<_i20.TvshowModel>[]),
      ) as _i8.Future<List<_i20.TvshowModel>>);

  @override
  _i8.Future<_i4.TvshowDetailResponse> getTvshowDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowDetail,
          [id],
        ),
        returnValue: _i8.Future<_i4.TvshowDetailResponse>.value(
            _FakeTvshowDetailResponse_2(
          this,
          Invocation.method(
            #getTvshowDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i4.TvshowDetailResponse>);

  @override
  _i8.Future<List<_i20.TvshowModel>> getTvshowRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowRecommendations,
          [id],
        ),
        returnValue:
            _i8.Future<List<_i20.TvshowModel>>.value(<_i20.TvshowModel>[]),
      ) as _i8.Future<List<_i20.TvshowModel>>);

  @override
  _i8.Future<List<_i20.TvshowModel>> searchTvshow(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvshow,
          [query],
        ),
        returnValue:
            _i8.Future<List<_i20.TvshowModel>>.value(<_i20.TvshowModel>[]),
      ) as _i8.Future<List<_i20.TvshowModel>>);

  @override
  _i8.Future<_i5.SeasonDetailResponse> getTvshowSeasonDetail(
    int? seriesId,
    int? seasonId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowSeasonDetail,
          [
            seriesId,
            seasonId,
          ],
        ),
        returnValue: _i8.Future<_i5.SeasonDetailResponse>.value(
            _FakeSeasonDetailResponse_3(
          this,
          Invocation.method(
            #getTvshowSeasonDetail,
            [
              seriesId,
              seasonId,
            ],
          ),
        )),
      ) as _i8.Future<_i5.SeasonDetailResponse>);
}

/// A class which mocks [TvshowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowRepository extends _i1.Mock implements _i21.TvshowRepository {
  MockTvshowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>
      getNowPlayingTvshows() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingTvshows,
              [],
            ),
            returnValue:
                _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                    _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
              this,
              Invocation.method(
                #getNowPlayingTvshows,
                [],
              ),
            )),
          ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>> getPopularTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvshows,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
          this,
          Invocation.method(
            #getPopularTvshows,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>> getTopRatedTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvshows,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
          this,
          Invocation.method(
            #getTopRatedTvshows,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i23.TvshowDetail>> getTvshowDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowDetail,
          [id],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i23.TvshowDetail>>.value(
                _FakeEither_0<_i9.Failure, _i23.TvshowDetail>(
          this,
          Invocation.method(
            #getTvshowDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i23.TvshowDetail>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>
      getTvshowRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvshowRecommendations,
              [id],
            ),
            returnValue:
                _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                    _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
              this,
              Invocation.method(
                #getTvshowRecommendations,
                [id],
              ),
            )),
          ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>> searchTvshows(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvshows,
          [query],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
          this,
          Invocation.method(
            #searchTvshows,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
          _i23.TvshowDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
          _i23.TvshowDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>
      getWatchlistTvshows() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistTvshows,
              [],
            ),
            returnValue:
                _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>.value(
                    _FakeEither_0<_i9.Failure, List<_i22.Tvshow>>(
              this,
              Invocation.method(
                #getWatchlistTvshows,
                [],
              ),
            )),
          ) as _i8.Future<_i2.Either<_i9.Failure, List<_i22.Tvshow>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i24.SeasonDetail>> getTvShowSeasonDetail(
    int? seriesId,
    int? seasonId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvShowSeasonDetail,
          [
            seriesId,
            seasonId,
          ],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i24.SeasonDetail>>.value(
                _FakeEither_0<_i9.Failure, _i24.SeasonDetail>(
          this,
          Invocation.method(
            #getTvShowSeasonDetail,
            [
              seriesId,
              seasonId,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i24.SeasonDetail>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i26.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i26.Uint8List>.value(_i26.Uint8List(0)),
      ) as _i8.Future<_i26.Uint8List>);

  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_5(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
